//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int Id_Login { get; set; }
        [DisplayName("Nome de Usuário")]
        
        public string Usuario { get; set; }
        [DataType(DataType.Password)] //Essa propriedade do componente DataAnnotations especificar que o campo oculte a senha do usuario
        public string Senha { get; set; }
        public string TipoUsuario { get; set; }
        public Nullable<bool> StatusUsuario { get; set; }

        public String ErroNoLogin { get; set; }
    }
}
